-- Portfolio version of the original IDS coursework
-- Oracle SQL

-- Drop objects if they already exist. Ignore "object does not exist" errors on first run.
BEGIN EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW branch_stock_mv'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE sold CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE located_at CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE sale CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE delivery CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE price_history CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE product CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE supplier CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE branch CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE branch (
    branch_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_name    VARCHAR2(255) NOT NULL,
    address        VARCHAR2(255) NOT NULL,
    phone_number   VARCHAR2(20)  NOT NULL,
    CONSTRAINT branch_phone_chk
        CHECK (REGEXP_LIKE(phone_number, '^\+[0-9]{12}$'))
);

CREATE TABLE product (
    product_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_type    VARCHAR2(10) NOT NULL,
    product_name    VARCHAR2(255) NOT NULL,
    weight          NUMBER NOT NULL,
    expiry_date     DATE NOT NULL,
    selling_price   NUMBER(10,2) NOT NULL,
    CONSTRAINT product_type_chk CHECK (product_type IN ('fruit', 'vegetable')),
    CONSTRAINT product_weight_chk CHECK (weight > 0),
    CONSTRAINT product_price_chk CHECK (selling_price > 0)
);

CREATE TABLE price_history (
    product_id   NUMBER NOT NULL,
    price_date   DATE NOT NULL,
    price        NUMBER(10,2) NOT NULL,
    CONSTRAINT price_history_pk PRIMARY KEY (product_id, price_date),
    CONSTRAINT price_history_product_fk
        FOREIGN KEY (product_id) REFERENCES product(product_id) ON DELETE CASCADE,
    CONSTRAINT price_history_price_chk CHECK (price > 0)
);

CREATE TABLE supplier (
    supplier_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name  VARCHAR2(255) NOT NULL,
    address       VARCHAR2(255) NOT NULL,
    phone_number  VARCHAR2(20) NOT NULL,
    email         VARCHAR2(255) NOT NULL,
    CONSTRAINT supplier_phone_chk
        CHECK (REGEXP_LIKE(phone_number, '^\+[0-9]{12}$')),
    CONSTRAINT supplier_email_chk
        CHECK (REGEXP_LIKE(email, '^([a-zA-Z0-9]+[_.\-]?)*[a-zA-Z0-9]+@([a-zA-Z0-9]+[.\-]?)*[a-zA-Z0-9]+\.[a-zA-Z]{2,}$'))
);

CREATE TABLE delivery (
    delivery_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id    NUMBER NOT NULL,
    delivery_date  DATE NOT NULL,
    total_price    NUMBER(10,2) NOT NULL,
    total_weight   NUMBER NOT NULL,
    item_count     NUMBER NOT NULL,
    CONSTRAINT delivery_supplier_fk
        FOREIGN KEY (supplier_id) REFERENCES supplier(supplier_id) ON DELETE CASCADE,
    CONSTRAINT delivery_price_chk CHECK (total_price > 0),
    CONSTRAINT delivery_weight_chk CHECK (total_weight > 0),
    CONSTRAINT delivery_items_chk CHECK (item_count > 0)
);

CREATE TABLE sale (
    sale_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_date      DATE NOT NULL,
    total_price    NUMBER(10,2) NOT NULL,
    total_weight   NUMBER NOT NULL,
    item_count     NUMBER NOT NULL,
    branch_id      NUMBER NOT NULL,
    CONSTRAINT sale_branch_fk
        FOREIGN KEY (branch_id) REFERENCES branch(branch_id) ON DELETE CASCADE,
    CONSTRAINT sale_price_chk CHECK (total_price > 0),
    CONSTRAINT sale_weight_chk CHECK (total_weight > 0),
    CONSTRAINT sale_items_chk CHECK (item_count > 0)
);

CREATE TABLE sold (
    sale_id      NUMBER NOT NULL,
    product_id   NUMBER NOT NULL,
    quantity     NUMBER NOT NULL,
    CONSTRAINT sold_pk PRIMARY KEY (sale_id, product_id),
    CONSTRAINT sold_sale_fk
        FOREIGN KEY (sale_id) REFERENCES sale(sale_id) ON DELETE CASCADE,
    CONSTRAINT sold_product_fk
        FOREIGN KEY (product_id) REFERENCES product(product_id) ON DELETE CASCADE,
    CONSTRAINT sold_quantity_chk CHECK (quantity > 0)
);

CREATE TABLE located_at (
    branch_id    NUMBER NOT NULL,
    product_id   NUMBER NOT NULL,
    quantity     NUMBER NOT NULL,
    CONSTRAINT located_at_pk PRIMARY KEY (branch_id, product_id),
    CONSTRAINT located_at_branch_fk
        FOREIGN KEY (branch_id) REFERENCES branch(branch_id) ON DELETE CASCADE,
    CONSTRAINT located_at_product_fk
        FOREIGN KEY (product_id) REFERENCES product(product_id) ON DELETE CASCADE,
    CONSTRAINT located_at_quantity_chk CHECK (quantity >= 0)
);
